= The mod_cluster Project Documentation

Welcome to the new mod_cluster live documentation!

== Contributing

How can I contribute?

* Get familiar with https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc].
* Open https://docs.modcluster.io and locate section you want to contribute to.
* Click 'Improve this page – edit on GitHub.' at the top of each section.
* If using an IDE, fork and clone the repository locally and navigate to `docs/src/main/asciidoc/` directory.
* Once finished editing, click 'Propose changes' which will open a new pull request.
* Pull request will be quickly reviewed by mod_cluster contributors, merged, and changes will be live almost instantly!

== Guidelines

* Documentation changes infrequently. To minimize the maintenance cost of multiple documentation versions, use wording similar to "Since version 1.3" to describe behavior changes across versions.
* Commit messages: you can describe changes you have done, or you could leave the default GitHub message which will just say "Update section.adoc".
* Use shorter lines to make rebasing and editing from the web slightly easier.
* Documentation always resides in `main` branch of the upstream (`modcluster/docs.modcluster.io`) repository.

== Building locally

The build uses Apache Maven with `mvn package`:

[source]
----
[rhusar@primitivo docs.modcluster.io]$ mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] mod_cluster docs (parent)                                          [pom]
[INFO] mod_cluster docs: Documentation                                    [pom]
[INFO]
[INFO] -----------< org.jboss.mod_cluster:mod_cluster-docs-parent >------------
[INFO] Building mod_cluster docs (parent) 2.0.0.Final-SNAPSHOT           [1/2]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ mod_cluster-docs-parent ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ mod_cluster-docs-parent ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-https-repositories) @ mod_cluster-docs-parent ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ mod_cluster-docs-parent ---
[INFO] Executing: /bin/sh -c cd '/Users/rhusar/git/docs.modcluster.io' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /Users/rhusar/git/docs.modcluster.io
[INFO] Storing buildNumber: 86586ad1ac5dbdb6b7995d387fe172135d1716d3 at timestamp: 1629720283364
[INFO] Storing buildScmBranch: main
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ mod_cluster-docs-parent ---
[INFO]
[INFO] ---------------< org.jboss.mod_cluster:mod_cluster-docs >---------------
[INFO] Building mod_cluster docs: Documentation 2.0.0.Final-SNAPSHOT     [2/2]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ mod_cluster-docs ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ mod_cluster-docs ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-https-repositories) @ mod_cluster-docs ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ mod_cluster-docs ---
[INFO]
[INFO] --- asciidoctor-maven-plugin:1.6.0:process-asciidoc (pdf) @ mod_cluster-docs ---
[INFO] AsciiDoc processing is skipped.
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ mod_cluster-docs ---
[INFO]
[INFO] --- asciidoctor-maven-plugin:1.6.0:process-asciidoc (output-html) @ mod_cluster-docs ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources to images
[INFO] Copying 1140 resources to .
[INFO] Rendered /Users/rhusar/git/docs.modcluster.io/docs/src/main/asciidoc/index.adoc
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for mod_cluster docs (parent) 2.0.0.Final-SNAPSHOT:
[INFO]
[INFO] mod_cluster docs (parent) .......................... SUCCESS [  0.549 s]
[INFO] mod_cluster docs: Documentation .................... SUCCESS [  3.608 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.255 s
[INFO] Finished at: 2021-08-23T14:04:47+02:00
[INFO] ------------------------------------------------------------------------
----

Resulting files are located in the `docs/target/generated-docs/` directory.

== Inner Workings

=== How does it work?

. Changes are proposed in a pull request for `docs.modcluster.io` repository.
. Changes are committed (merged) by a mod_cluster committer to the `main` branch.
. GitHub Actions detects the changes and runs a maven build, pushes the changes into `gh-pages` branch of the upstream repository.
. GitHub Pages picks up the changes and deploys the website.

NOTE: `CNAME` record is configured on the website pointing to GitHub servers.

=== Questions?

https://github.com/modcluster/mod_cluster/discussions
