var annotated_dup =
[
    [ "balancer_method", "structbalancer__method.html", "structbalancer__method" ],
    [ "balancer_storage_method", "structbalancer__storage__method.html", "structbalancer__storage__method" ],
    [ "balancerinfo", "structbalancerinfo.html", "structbalancerinfo" ],
    [ "cluster_host", "structcluster__host.html", "structcluster__host" ],
    [ "context_storage_method", "structcontext__storage__method.html", "structcontext__storage__method" ],
    [ "contextinfo", "structcontextinfo.html", "structcontextinfo" ],
    [ "counter", "structcounter.html", "structcounter" ],
    [ "domain_storage_method", "structdomain__storage__method.html", "structdomain__storage__method" ],
    [ "domaininfo", "structdomaininfo.html", "structdomaininfo" ],
    [ "host_storage_method", "structhost__storage__method.html", "structhost__storage__method" ],
    [ "hostinfo", "structhostinfo.html", "structhostinfo" ],
    [ "ma_advertise_hdr_t", "structma__advertise__hdr__t.html", "structma__advertise__hdr__t" ],
    [ "ma_advertise_srv_t", "structma__advertise__srv__t.html", "structma__advertise__srv__t" ],
    [ "ma_global_data_t", "structma__global__data__t.html", "structma__global__data__t" ],
    [ "mem", "structmem.html", "structmem" ],
    [ "mod_advertise_config", "structmod__advertise__config.html", "structmod__advertise__config" ],
    [ "node_context", "structnode__context.html", "structnode__context" ],
    [ "node_storage_method", "structnode__storage__method.html", "structnode__storage__method" ],
    [ "nodeinfo", "structnodeinfo.html", "structnodeinfo" ],
    [ "nodemess", "structnodemess.html", "structnodemess" ],
    [ "proxy_balancer_table", "structproxy__balancer__table.html", "structproxy__balancer__table" ],
    [ "proxy_cluster_helper", "structproxy__cluster__helper.html", "structproxy__cluster__helper" ],
    [ "proxy_context_table", "structproxy__context__table.html", "structproxy__context__table" ],
    [ "proxy_node_table", "structproxy__node__table.html", "structproxy__node__table" ],
    [ "proxy_vhost_table", "structproxy__vhost__table.html", "structproxy__vhost__table" ],
    [ "sessionid_storage_method", "structsessionid__storage__method.html", "structsessionid__storage__method" ],
    [ "sessionidinfo", "structsessionidinfo.html", "structsessionidinfo" ],
    [ "version_data", "structversion__data.html", "structversion__data" ],
    [ "watchdog_thread_args", "structwatchdog__thread__args.html", "structwatchdog__thread__args" ]
];