ifeval::["{backend}" == "html5"]
TIP: This document is also available as a link:mod_cluster-v2-user-guide.pdf[PDF to download].
endif::[]

[[overview]]
= Overview

NOTE: {editurl}introduction.adoc[{editnote}]

Project mod_cluster is an intelligent load balancer. Like mod_jk and
mod_proxy, mod_cluster uses a communication channel to forward
requests from httpd to one of a set of application server nodes. Unlike
mod_jk and mod_proxy, mod_proxy_cluster leverages an additional connection
between the application server nodes and httpd. The application server
nodes use this connection to transmit server-side load balance factors
and lifecycle events back to httpd via a custom set of HTTP methods,
affectionately called the Mod-Cluster Management Protocol (MCMP). This
additional feedback channel allows mod_proxy_cluster to offer a level of
intelligence and granularity not found in other load balancing
solutions.

Within httpd, mod_proxy_cluster is implemented as a set of modules for httpd
with mod_proxy enabled. Much of the logic comes from mod_proxy, e.g.
mod_proxy_ajp provides all the AJP logic needed by mod_proxy_cluster.

NOTE: In the past, mod_proxy_cluster was named mod_cluster (version 1.3.x and older),
consisting of native and container implementations. The repositories of the two
implementations were separated, and the native part got the name mod_proxy_cluster, while
the former name mod_cluster is currently used for container implementation.

[[support-matrix]]
== Support Matrix

=== Container Integration Modules

|===
| Release | Tomcat versions | Code | Documentation

| `2.1` (in development) | `11.0`, `10.1`, `9.0` | https://github.com/modcluster/mod_cluster/tree/main[SCM Branch] | https://docs.modcluster.io/apidocs/2.1/[Javadoc]
| `2.0` | `10.1`, `9.0`, `8.5` (EOL) | https://github.com/modcluster/mod_cluster/tree/2.0.x[SCM Branch] | https://docs.modcluster.io/apidocs/2.0/[Javadoc]
| `1.4` |  `9.0`, `8.5` (EOL), `8.0` (EOL), `7.0` (EOL) | https://github.com/modcluster/mod_cluster/tree/1.4.x[SCM Branch] | https://docs.modcluster.io/apidocs/1.4/[Javadoc]
|===

=== Apache HTTP modules

|===
| Release | httpd versions | Code | Documentation

| `2.0` (in development) | 2.4.53 and newer | https://github.com/modcluster/mod_proxy_cluster/tree/main[SCM Branch] | https://docs.modcluster.io/apidocs/mpc-2.0/[Doxygen]
| `1.3` | 2.4.49 and newer | https://github.com/modcluster/mod_cluster/tree/1.3.x[SCM Branch] |
|===

Complete documentation for legacy versions is archived at https://docs.modcluster.io/legacy/.

[[platforms]]
== Platforms

The binary packages of the modules needed to use with Apache httpd server are present in most distributions.

If your distribution doesn't provide mod_proxy_cluster, pick the latest version from the source and follow
the building instructions.

[[advantages]]
== Advantages
mod_proxy_cluster boasts the following advantages over other httpd-based load balancers:

* Dynamic configuration of httpd workers

Traditional httpd-based load balancers require explicit configuration of the workers available to a proxy.
In mod_proxy_cluster, the bulk of the proxy's configuration resides on the application servers. The set of
proxies to which an application server will communicate is determined either by a static list or using dynamic
discovery via the advertising mechanism. The application server relays lifecycle events (e.g. server startup/shutdown)
to the proxies allowing them to effectively autoconfigure themselves. Notably, the graceful shutdown of a server
will not result in a failover response by a proxy, as is the case with traditional httpd-based load balancers.

* Server-side load balance factor calculation

In contrast with traditional httpd-based load balancers, mod_proxy_cluster uses load balance factors calculated and
provided by the application servers rather than computing these in the proxy. Consequently, mod_proxy_cluster offers
a more robust and accurate set of load metrics than is available from the proxy (see Load Metrics for more).

* Fine-grained web-app lifecycle control

Traditional httpd-based load balancers do not handle web application undeployments particularly well. From the proxy's
perspective, requests to an undeployed web application are indistinguishable from a request for a non-existent
resource and will result in 404 errors. In mod_cluster, each server forwards any web application context lifecycle
events (e.g. web-app deploy/undeploy) to the proxy, informing it to start/stop routing requests for a given context to
that server.

* AJP is optional

Unlike mod_jk, mod_proxy_cluster does not require AJP. httpd connections to application server nodes can use HTTP, HTTPS, or AJP.
The original concepts are described in a xref:developer/design.adoc[Design] article.

== Requirements

=== Balancer side

* Apache HTTP Server 2.4.53 and newer for mod_proxy_cluster 2.x
* Apache HTTP Server 2.4.49 and newer for mod_proxy_cluster/mod_cluster 1.3.x

=== Worker side

The mod_cluster container integration module (implemented in Java) is provided for all the following containers:

* WildFly 8 and newer
* JBoss AS 7
* Tomcat 6 and newer

== Limitations

mod_proxy_cluster uses shared memory to keep the nodes description, the shared memory is created at the start of httpd and
the structure of each item is fixed. The following cannot be changed by configuration directives.

* Max Alias length 255 characters in 2.x, 100 characters in 1.3.x (Host: hostname header, Alias in&lt;Host/&gt;).
* Max context length 80 (for example myapp.war deploys in /myapp/myapp is the context).
* Max balancer name length 40 (balancer property in mbean).
* Max JVMRoute string length is PROXY_WORKER_MAX_ROUTE_SIZE characters in 2.x, 64 characters in 1.3.x (JVMRoute in &lt;Engine/&gt;).
* Max load balancing group name length 20 (domain property in mbean).
* Max hostname length for a node 64 (address in the &lt;Connector/&gt;).
* Max port length for a node 7 (8009 is 4 characters, port in the &lt;Connector/&gt;).
* Max scheme length for a node 16 (possible values are http, https, ajp, liked with the protocol of &lt;Connector/&gt;).
* Max cookie name 30 (the header cookie name for sessionid default value: `JSESSIONID` from `org.apache.catalina.Globals.SESSION_COOKIE_NAME`).
* Max path name 30 (the parameter name for the sessionid default value: `jsessionid` from `org.apache.catalina.Globals.SESSION_PARAMETER_NAME`).
* Max length for a sessionid 120 (something like BE81FAA969BF64C8EC2B6600457EAAAA.node01).

== Downloads

Download the latest https://modcluster.io/downloads/[mod_cluster release].

The release contains the source to build the WildFly/JBoss AS/Tomcat Java distributions

The native part is developed in https://github.com/modcluster/mod_proxy_cluster (with 1.3.x version and older
available in the original repository https://github.com/modcluster/mod_cluster/tree/1.3.x).
The native part is compatible with the 2.0.x and 1.4.x branches of mod_cluster

Alternatively, you can build from source using the https://github.com/modcluster/mod_cluster[mod_cluster git repository]
and https://github.com/modcluster/mod_proxy_cluster[mod_proxy_cluster git repository].

== Configuration

If you want to skip the details and just set up a minimal working
installation of mod_cluster, see the link:#quick-start-guide[Quick Start Guide].

* Configuring link:#httpd[balancer]
* Configuring link:#container-integration-configuration[workers]

[[migration]]
== Migration from mod_jk or mod_proxy

Migrating from mod_jk or mod_proxy is fairly straightforward. In general, much of the configuration previously
found in `httpd.conf` is now defined in the application server worker nodes.

* Migrating from link:#migration-from-mod_jk[mod_jk]
* Migrating from link:#migration-from-mod_proxy[mod_proxy]

== SSL support

Both the request connections between httpd and the application server nodes, and the feedback channel
between the nodes and httpd can be secured. The former is achieved via the mod_proxy_https module and a corresponding
ssl-enabled HTTP connector in JBoss Web or Undertow. The latter requires the link:#using-ssl-in-mod_cluster[mod_ssl
module] and link:#ssl-configuration[explicit configuration in WildFly/JBoss AS/Web/Undertow].

mod_cluster contains mod_ssl, therefore the warning (copied from OpenSSL https://www.openssl.org/[website]).

WARNING: Strong cryptography: Please remember that export/import and/or use of strong cryptography software, providing
cryptography hooks, or even just communicating technical details about cryptography software is illegal in some parts
of the world. So when you import this package to your country, re-distribute it from there or even just email technical
suggestions or even source patches to the authors or other people you are strongly advised to pay close attention to
any laws or regulations which apply to you. The authors of openssl are not liable for any violations you make here. So
be careful, it is your responsibility.

