= Quick Start Guide

NOTE: {editurl}quickstart.adoc[{editnote}]

Following are the steps to set up a minimal working installation of
mod_cluster on a single httpd server and a single back end server,
either JBoss AS, JBossWeb, Undertow or Tomcat. The steps can be repeated to add as
many httpd servers or back end servers to your cluster as desired.

The steps shown here are not intended to demonstrate how to set up a production
install of mod_proxy_cluster; for example, link:#using-ssl-in-mod_cluster[using SSL
to secure access] to the httpd-side mod_manager component is not covered. See the
link:#httpd[balancer-side] and link:#container-integration-configuration[worker-side]
configuration documentation for the full set of configuration options.

== Download mod_cluster components

Download the latest httpd and java release bundles.
If there is no pre-built httpd bundle appropriate for your OS or system architecture,
you can link:#building-httpd-modules[build the Apache httpd binary from the source].

== Install the httpd binary

=== Install the whole httpd

Most of the standard distributions contain Apache httpd server. Use your platform's
specific install tools to install. For example, in Fedora, just install as a root:

[source,bash]
----
dnf install httpd
----

=== Install only the mod_cluster modules

If you already have a working httpd install that you would prefer to
use and your distribution contains mod_cluster/mod_proxy_cluster just install it:

[source,bash]
----
dnf install mod_cluster
----

And then you have the files below in your module directory:

* mod_manager.so
* mod_proxy_cluster.so
* mod_advertise.so
* mod_cluster_slotmem.so (only 1.3.x version)

*httpd version mismatch:* `[warn] httpd version mismatch detected` Please,
beware that one cannot simply load the aforementioned modules into an arbitrary
httpd installation. These modules were built with a particular minor httpd
version, and they cannot be used with an older one.

=== Install in Windows

Unzip the bundle corresponding to your architecture.
Change to the bin directory of the subfolder `Apache24` where you unzipped the bundle.

You may run httpd directly by using:

[source]
----
httpd.exe
----

or install Apache HTTP Server as a service:

[source]
----
httpd.exe -k install -n myApache
----

and start the service via net start or using httpd.exe:

[source]
----
net start myApache
----

or

[source]
----
httpd.exe -k start
----

== Configure httpd

httpd.conf might need to be configured to use mod_proxy_cluster.

[source]
----
LoadModule proxy_module         modules/mod_proxy.so
LoadModule proxy_http_module    modules/mod_proxy_http.so
LoadModule proxy_ajp_module     modules/mod_proxy_ajp.so
LoadModule manager_module       modules/mod_manager.so
LoadModule proxy_cluster_module modules/mod_proxy_cluster.so
LoadModule advertise_module     modules/mod_advertise.so
LoadModule watchdog_module      modules/mod_watchdog.so
LoadModule slotmem_shm_module   modules/mod_slotmem_shm.so

<IfModule manager_module>
  Listen 127.0.0.1:6666
  ManagerBalancerName mycluster
  <VirtualHost 127.0.0.1:6666>
    <Location />
     Require ip 127.0.0
    </Location>

    EnableMCPMReceive
    <Location /mod_cluster_manager>
       SetHandler mod_cluster-manager
       Require ip 127.0.0
    </Location>

  </VirtualHost>
</IfModule>
----

For mod_proxy_cluster/mod_cluster 1.3.x you must load mod_cluster_slotmem module instead
of the httpd's one. Simply change the line with `slotmem_shm_module` to following:

[source]
----
LoadModule cluster_slotmem_module modules/mod_cluster_slotmem.so
----

== Install the worker-side binaries

Build the jar file using maven
[source]
----
mvn install
----

Your next step depends on whether your target server is JBoss AS 7.x, Tomcat 8, 8.5/9.0 or 10.x or WildFly (Undertow).

=== Installing in Tomcat

Assuming $CATALINA_HOME indicates the root of your Tomcat install:

[source,bash]
----
cp container/tomcat-[8.5,9.0,10.1]/target/*.jar $CATALINA_HOME/lib/
cp container/spi/target/*.jar $CATALINA_HOME/lib/
cp load-spi/target/*.jar $CATALINA_HOME/lib/
cp core/target/*.jar $CATALINA_HOME/lib/
cp dist/target/dependency/jboss-logging* $CATALINA_HOME/lib/
----

Note that you should copy only the tomcat files corresponding to your tomcat installation.

* tomcat-8.5 for tomcat 8.5.x

* tomcat-9.0 for tomcat 9.0.x

* tomcat-10.1 for tomcat 10.0.x and 10.1.x

=== Installing in WildFly

WildFly already includes mod_cluster integration so no extra installation steps are necessary. 
The mod_cluster subsystem is pre-configured in the HA configurations.
For WildFly-specific configuration refer to https://docs.wildfly.org/[WildFly documentation].

== Configuring the server-side

=== Configuring mod_cluster with JBoss AS 5.x+

No post-installation configuration necessary!

=== Configuring mod_cluster with standalone JBoss Web or Tomcat

Edit the `$CATALINA_HOME/conf/server.xml` file, adding the following next to the other `&lt;Listener/&gt;` elements:

[source,xml]
----
<Listener className="org.jboss.modcluster.container.catalina.standalone.ModClusterListener" proxyList="127.0.0.1:6666"/>
----

=== Start httpd

To start httpd do the following:

[source,bash]
----
/opt/jboss/httpd/sbin/apachectl start
----

=== Start the back-end server

==== Starting JBoss AS

[source,bash]
----
cd $JBOSS_HOME/bin
./run.sh -c all
----

==== Starting JBossWeb or Tomcat

[source,bash]
----
cd $CATALINA_HOME
./startup.sh
----

==== Set up more back-end servers

Repeat the back-end server install and configuration steps for each
server in your cluster.

== Experiment with the Load Balancing Demo Application

See link:#demo[demo].

