[[mcmp]]
= ModCluster Management Protocol (MCMP)

NOTE: {editurl}management_protocol.adoc[{editnote}]

This document describes elements of the <<design,ModCluster>> Management Protocol for communication between a container (AS)
and a load balancer (Apache httpd / Undertow).

== Messages

|===
| Message type / Request method | Description

| CONFIG      | Send configuration information for a node or set of nodes.
| INFO        | Request configuration info from mod_cluster-manager.
| DUMP        | Request a text dump of the current configuration seen by mod_cluster_manager.
| STATUS      | Send the current load balance factor for this node (or a set of nodes). Periodically sent.
| PING        | Request a ping to httpd or node. The node could defined by JVMRoute or Scheme, Host, and Port (since version 0.1.0).
| VERSION     | Request information about the software version used and supported MCMP version
| ENABLE-APP  | Send requests and assign new sessions to the specified app. Use of to identify the app means enable all apps on the given node.
| DISABLE-APP | Apache should not create new session for this webapp, but still continue serving existing session on this node. Use of to identify the app means disable all apps on the given node.
| STOP-APP    | New requests for this webapp should not be sent to this node. Use of to identify the app means stop all apps on the given node.
| REMOVE-APP  | Remove the information about this webapp from mod_cluster tables.
|===

=== Message payload

The information is in ASCII and URL encoded if needed.

All numbers are integers, string representation is used.

The command is a string in the first part of a message followed by `/ HTTP/1.0<CR><LF>`.

Example:

[source]
----
DISABLE-APP / HTTP/1.0<CR><LF>
----

All parameters are send as <PARAMETER_NAME>=<VALUE> and the separator between
their pairs is <&>

<SPACE> in value is escaped as <+>

<&> in value is escaped as &26

\<\=> in value is escaped %3D

<CR><LF> means end of <COMMAND>

For certain values you can specify a list, in such cases separate the individual values by commas
(e.g., `Alias=localhost,demo`).

NOTE: All parameter names are case insensitive, but their values are NOT.

Example:

[source]
----
DISABLE-APP / HTTP/1.0<CR><LF>

Content-length: 44<CR><LF>

<CR><LF>

Jvmroute=node1&Context=/myapp&Alias=demo<CR><LF>
----

You can send the command using `curl` executing following:

[source]
----
curl -XDISABLE-APP -d "JVMRoute=node1" -d "Context=/myapp" -d "Alias=demo" http://localhost:6666
----

== Message Types

Following are the descriptions of individual message types with their parameters.

=== CONFIG

This message adds a new node or updates an existing one.

|===
| Key      | Description                                                                                                       | Default   | Required

| Alias    | List of virtual hosts (See http://tomcat.apache.org/tomcat-6.0-doc/config/host.html#Host%20Name%20Aliases[Alias]) |           |
| Balancer | is the name of the balancer in httpd (for example mycluster in ProxyPass /myapp balancer://mycluster/)            | mycluster |
| Context  | List the context the virtual host list supports like (Ex. "/myapp,/ourapp")                                       |           |
| Domain   | is the domain corresponding to the node                                                                           |           |
| Host     | is the IP address (or hostname) where the node is going to receive requests from httpd                            | localhost |
| JVMRoute | Is what is after the . in the JSESSIONID cookie or the parameter jsessionid                                       |           | Yes
| Port     | is the port on which the node except to receive requests                                                          | 8009      |
| Type     | http/https/ajp The protocol to use between httpd and AS to process requests                                       | ajp       |

| Reversed            | Reverse connection | no |
| Flushpackets        | Enables/disables packet flushing (values: on/off/auto) | off |
| Flushwait           | Time to wait before flushing packets in milliseconds. A value of -1 means wait forever | PROXY_FLUSH_WAIT |
| Ping                | Time (in seconds) in which to wait for a pong answer to a ping | 10 seconds |
| Smax                | Soft maximum idle connection count (that is the smax in worker mod_proxy documentation). The maximum value depends on the httpd thread configuration (ThreadsPerChild or 1) | -1 |
| Ttl                 | Time to live (in seconds) for idle connections above smax (in seconds) | 60 seconds |
| Timeout             | Timeout (in seconds) for proxy connections to a node. That is the time mod_cluster will wait for the back-end response before returning error. That corresponds to timeout in the worker mod_proxy documentation. A value of -1 indicates no timeout. Note that mod_cluster always uses a cping/cpong before forwarding a request and the connectiontimeout value used by mod_cluster is the ping value | 0 |
| StickySession       | Indicates whether subsequent requests for a given session should be routed to the same node, if possible | yes |
| StickySessionCookie | Value of the Session cookie  | JSESSIONID |
| StickySessionPath   | Value of the Session path    | jsessionid |
| StickySessionRemove | Indicates whether the httpd proxy should remove session stickiness in the event that the balancer is unable to route a request to the node to which it is stuck. Ignored if stickySession is false | no |
| StickySessionForce  | Indicates whether the httpd proxy should return an error in the event that the balancer is unable to route a request to the node to which it is stuck. Ignored if stickySession is false           | yes |
| WaitWorker          | Number of seconds to wait for a worker to become available to handle a request. When no workers of a balancer are usable, mod_cluster will retry after a while (workerTimeout/100). That is timeout in the balancer mod_proxy documentation. A value of -1 indicates that the httpd will not wait for a worker to be available and will return an error if none is available (in seconds) | 0 |
| MaxAttempts         | Maximum number of failover attempts before giving up. The minimum value is 0, i.e. no failover. The default value is 1, i.e. do a one failover attempt | 1 |
|===

NOTE: There are some limitations with regard to maximal lengths of some values. See
https://docs.modcluster.io/#limitations[Limitations] section for more information.

The response in case of success is empty with HTTP code 200. In case of an error, HTTP 500 response is sent with header values `Type` and `Mess` set
containing the type of the error and its description respectively. See the <<Error handling>> section for more information.


=== INFO

This message doesn't expect parameters, but you can supply an `Accept` header specifying the context type of the response. If `"text/xml"`
is specified, the response will contain an XML. Otherwise plain text response is sent.

The plain text format has a following structure:

[source]
----
<Nodes>
<Hosts>
<Contexts>
----

where <Nodes> are 0 or more node records separated by a newline where each node record has following structure:

[source]
----
Node: [<number>],Name: <JVMRoute value>,Balancer: <Balancer name>,LBGroup: <LBGroup>,Host: <Host name>,Port: <port value>,Type: <scheme/protocol to use>,Flushpackets: <value>,Flushwait: <value>,Ping: <value>,Smax: <value>,Ttl: <value>,Elected: <value>,Read: <value>,Transfered: <value>,Connected: <value>,Load: <value>
----

NOTE: For definitions of the individual values see the corresponding documentation section describing related
https://docs.modcluster.io/#mod_proxy_cluster[directives].

<Hosts> are 0 or more records separated by a newline where each host record has following structure:

[source]
----
Vhost: [<number>:<number>:<number>], Alias: <alias value>
----

and <Contexts> are 0 or more records separated by a newline where each record has following structure:

[source]
----
Context: [<number>:<number>:<number>], Context: <context value>, Status: <one of ENABLED, STOPPED, DISABLED>
----

NOTE: The first field in each of the described records is intended for debugging purposes and are present only in the text representation.

Example:

[source]
----
Node: [0],Name: spare,Balancer: mycluster,LBGroup: ,Host: localhost,Port: 8888,Type: ws,Flushpackets: Off,Flushwait: 10,Ping: 10,Smax: -1,Ttl: 60,Elected: 0,Read: 0,Transfered: 0,Connected: 0,Load: 0
Node: [1],Name: test,Balancer: mycluster,LBGroup: ,Host: localhost,Port: 8889,Type: ws,Flushpackets: Off,Flushwait: 10,Ping: 10,Smax: -1,Ttl: 60,Elected: 0,Read: 0,Transfered: 0,Connected: 0,Load: -1
Vhost: [1:1:0], Alias: localhost
Context: [1:1:0], Context: test, Status: STOPPED
----

TODO: Desribe the XML format.

=== DUMP

This message doesn't expect parameters, but you can supply an `Accept` header specifying the context type of the response. If `"text/xml"`
is specified, the response will contain an XML. Otherwise plain text response is sent.

The plain text format has a following structure:

[source]
----
<Balancers>
<Nodes>
<Hosts>
<Contexts>
----

where the individual sections contain 0 or more records separated by a newline. The structure is similar to the corresponding
the records of INFO response, however, there are a few differences such as missing commas in most of the cases.

The balancer records have the following structure:

[source]
----
balancer: [<number>] Name: <balancer name> Sticky: <value> [<Sticky session cookie]/[Sticky session path] remove: <value> force: <value> Timeout: <value> maxAttempts: <value>
----

The structure of node records is following:

[source]
----
node: [<number>:<number>],Balancer: <balancer name>,JVMRoute: <value>,LBGroup: [<value>],Host: <value>,Port: <value>,Type: <value>,flushpackets: <value>,flushwait: <value>,ping: <value>,smax: <value>,ttl: <value>,timeout: <value>
----

The host structure:

[source]
----
host: <number> [<host/alias value>] vhost: <number - host id> node: <number - node id>
----

and finally the context structure:

[source]
----
context: <number> [<context value>] vhost: <number - host id> node: <number - node id> status: <1 for ENABLED, 2 for DISABLED, 3 for STOPPED>
----

NOTE: The first field in described records is intended for debugging purposes and are present only in the text representation.

Example:

[source]
----
balancer: [0] Name: mycluster Sticky: 1 [JSESSIONID]/[jsessionid] remove: 0 force: 1 Timeout: 0 maxAttempts: 1
node: [0:0],Balancer: mycluster,JVMRoute: spare,LBGroup: [],Host: localhost,Port: 8888,Type: ws,flushpackets: 0,flushwait: 10,ping: 10,smax: -1,ttl: 60,timeout: 0
node: [1:1],Balancer: mycluster,JVMRoute: test,LBGroup: [],Host: localhost,Port: 8889,Type: ws,flushpackets: 0,flushwait: 10,ping: 10,smax: -1,ttl: 60,timeout: 0
host: 0 [localhost] vhost: 1 node: 1
context: 0 [test] vhost: 1 node: 1 status: 3
----

TODO: Describe the XML output.


=== STATUS

The STATUS command requires single `JVMRoute` parameter specifying the node for which we want know the status. Optionally, you can supply `Load` parameter with
a numerical value that will set the `Load` factor for the target node.

In case of success, HTTP response with code 200 is sent with following parameters:

* `Type` with value `STATUS-RSP`
* `JVMRoute` corresponding to the value sent
* `State` with value `OK` or `NOK`
* `id` with a numerical value that is the generation id of process in httpd if it changes (increases) when httpd has been restarted and its view of the cluster
configuration could be incorrect. In this case ModClusterService should send a new CONFIG ASAP so the information could be updated.

In case of an error, HTTP 500 response is sent with headers `Type` and `Mess` set to the type and description of the error.

Example:

[source]
----
Type=STATUS-RSP&JVMRoute=spare&State=OK&id=698675605
----


=== PING

The `PING` command does not require any parameter, but there are a few optional parameters you can use changing the command behavior. See
the table below.

|===
| Key      | Description                                                                            | Required

| JVMRoute | Is what is after the . in the JSESSIONID cookie or the parameter jsessionid            | No
| Host     | is the IP address (or hostname) where the node is going to receive requests from httpd | Yes if Scheme or Port is specified
| Port     | is the port on which the node except to receive requests                               | Yes if Host or Scheme is specified
| Scheme   | http/https/ajp The protocol to use between httpd and AS to process requests            | Yes if Host or Port is specified
|===

If no parameter is supplied, then the `PING` checks whether the proxy if alive. In case `JVMRoute` is specified, then the corresponding node
is checked. When `Host`, `Port`, and `Scheme` are used, then it is checked whether httpd can reach a possible node using `Scheme://Host:Port`.
In case all parameters are specified, only `JVMRoute` is used and the behavior is the same as if the other ones were not present.


=== VERSION

This command requests the information about the used version and supported MCMP version. The HTTP 200 response has following format:

[source]
----
release: <software version>, protocol: <supported MCMP version>
----

so for example this is a valid response:

[source]
----
release: mod_cluster/1.3.20.Final, protocol: 0.2.1
----


=== ENABLE-APP

This command enables an application under the corresponding context and alias. If the application doesn't exist, an existing virtual host
is updated or a new one is created (that depends on the context/alias values).

// TODO: Maybe add a more verbose description with examples 
The insert/update logic works as follows: the proxy server goes through all received aliases and if any of them matches an
existing virtual host (first match), an update occurs. If there is no match, then a new virtual host is created.

|===
| Key      | Description                                                     | Required

| JVMRoute | JVMRoute on which we enable the application                     | Yes
| Context  | List of context under which the application should be deployed  | Yes if the request path is not `/*`
| Alias    | List of aliases for the corresponding virtual host              | Yes if the request path is not `/*`
|===

In case of success, an empty HTTP response with code 200 is sent. When an error occurs, HTTP 500 response is sent with `Type` and `Mess`
headers containing the details.

===  DISABLE-APP

Same as ENABLE-APP only sets the app status to DISABLED.

=== STOP-APP

Same as ENABLE-APP only sets the app status to STOPPED.

=== REMOVE-APP

Same as ENABLE-APP but removes the app from the proxy.


== Error handling

Once an error occurs during the MCMP communication, an HTTP response with code 500 is returned. The response contains headers
containing more details about the nature of the error. Namely `Type` and `Mess` header fields.


For example

[source]
----
HTTP/1.1 500 Internal Server Error
Date: Wed, 11 Sep 2024 13:45:44 GMT
Server: Apache/2.4.62 (Unix) mod_cluster/2.0.0.Alpha1-SNAPSHOT
Version: 0.2.1
Type: SYNTAX
Mess: Can't parse MCMP message. It might have contained illegal symbols or unknown elements.
Content-Length: 528
Connection: close
Content-Type: text/html; charset=iso-8859-1

<some html>
----

where

* Version is the supported version of the ModCluster Management Protocol.

* Type specifies type of the error (e.g., `SYNTAX` when the message is not formed correctly or `MEM` when the data cannot be
updated in or read from the shared memory).

* Mess is the message describing the error in more detail

== mod_cluster-manager handler

The mod_cluster-manager handler allows to do operation like
ENABLE-APP/DISABLE-APP through a web interface. The format of the request
string is the following:

[source]
----
Nonce:<nonce>&Cmd:<cmd>&Range:<range>&<MCMP String>
----

where:

* <nonce> Is a string like e17066b4-0cb1-4e58-93e3-cdc9efb6be9 corresponding to a unique id of httpd.
* <cmd> Is the command: one of ENABLE-APP, DISABLE-APP etc.
* <range> Is a "NODE" or "CONTEXT". "NODE" means that the -APP command is a wildcard command.
* <MCMP String> is a string containing a command described above.

Example:

[source]
----
http://localhost:8000/mod_cluster-manager?nonce=e17066b4-0cb1-4e58-93e3-cdc9efb6be9c&Cmd=DISABLE-APP&Range=CONTEXT&JVMRoute=jvm1&Alias=
----

== Miscellaneous

(<<design,ModCluster Design>> suggests that
ModClusterManager should wait until all sessions have been finished but that
requires a to be written tool. The idea is that an administrator initiated
step; similar to what people do now by changing workers.properties to quiesce a
node in mod_jk, but it could be initiated from the JBoss side via a management
tool). If a request arrives for a context corresponding to this node 500 will
be returned to the client.

An additional utility could be written to send a REMOVE-APP once the JBoss node
is stopped REMOTE-APP will remove all the node information from mod_cluster
table and any socket between httpd and the node will be closed. (For a more
complete description see <<internals,ModCluster Internals>>.) If
a request arrives for a context corresponding to this node 404 will be returned
to the client: in fact the mod_proxy will not be called for the request and an
httpd page could be displayed. A REMOVE-APP / for example will just clean the
mod_cluster table corresponding to the application defined in the payload.


